/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package pojos;

/**
 *
 * @author marta
 */
public enum ProtocolType {CARDIOARREST,CARDIOARREST_ELECTROCUTION, 
CARDIOARREST_MAJORTRAUMA,CARDIOARREST_MAJORTRAUMA_BLEEDING,CAR,CARDIOARREST_CAR,CARDIOARREST_CAR_BLEEDING,
PARTIAL_CHOKING,TOTAL_CHOKING,HEART_ATTACK,FAINTING,FAINTING_VOMIT,DIZZINESS, 
CONS_SEVERE_BLEEDING,SEIZURE,POISONING,ANAPHYLAXIS_VOMIT,ANAPHYLAXIS,STROKE,NOEMERGENCYFOUND,
MAJOR_TRAUMA,MAJOR_TRAUMA_BLEEDING,CAR_BLEEDING, CALL_112}
