/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package pojos;

/**
 *
 * @author marta
 */
public enum ProtocolType {NOEMERGENCYFOUND, CARDIO_ARREST, ELECTROCUTION_NO_BURN, MAJOR_TRAUMA_SEVERE_BLEEDING_NO_CAR_ACCIDENT, 
CONS_BREATH_MAJOR_TRAUMA_SEVERE_BLEEDING_NO_CAR, MAJOR_TRAUMA_CAR_ACCIDENT_CONS_BREATHING, MAJOR_TRAUMA_CAR_ACCIDENT_NO_BREATH_SEVERE_BLEEDING, 
MAJOR_TRAUMA_CAR_ACCIDENT_CONS_BREATH_SEVERE_BLEEDING, BREATHING_PROBLEMS_CONSCIOUS, SEVERE_BREATHING_PROBLEMS_HEIMLICH, CONS_BREATHING_NO_MAJ_TRAUMA_LEGS_UP, 
CONS_BREATHING_NO_MAJ_TRAUMA_RECOVERY_POS, DIZZINESS_LAY_DOWN, CONS_SEVERE_BLEEDING_PRESSURE, SEIZURE_NO_BREATHING, INTOXICATION_BREATHING_PROBLEMS, 
ALLERGIC_REACTION_WITH_VOMIT, ALLERGIC_REACTION_WITHOUT_VOMIT, DIZZY_WITH_BREATHING_PROBLEMS, MAJOR_TRAUMA_CAR_ACCIDENT_NO_BREATHING, 
MAJOR_TRAUMA_NO_CAR_ACCIDENT_NO_BREATHING, SEVERE_BLEEDING_NO_MAJOR_TRAUMA, CONS_BREATHING_NO_BLEEDING_MAJOR_TRAUMA_NO_CAR, CONS_BREATHING_SEVERE_BLEEDING_NO_MAJOR_TRAUMA}
